### ISSUE TITLE
Not notifications are sent on production and users do not create bindings

### ISSUE THREAD

**Issue by benSmith1981** [twilio/twilio-chat-ios#6] opened 2019-04-03 17:51 UTC
Users can create, invite and join channels together. Send messages. BUt no bindings are created and therefore (I assume you need to create a binding to user notifications) no notifications happen. I don't understand why this is. I waste a lot of time on this issue as it sporadically keeps coming up and despite trying everything I don't understand the issue. I don't even get a debug suggestion, which I used to as it was using the incorrect certificate.

WHat could be the issue? How do I fix it? The notifications have worked but now they seem to have just miraculously stopped working...

**Comment by Gray-Wind** [comment] 2019-11-18 12:29
Is this issue still reproducible for you?

**Comment by AdamBCo** [comment] 2019-12-11 20:11
@Gray-Wind I'm experiencing this issue as we speak.

On a other note I am receiving the following error message when using the registerWithNotificationToken function: Address of Apn Binding must be a nonempty string of even number of hexadecimal characters, statusCode: 400, HTTP status: Bad Request, public error code: 20001.

**Comment by berkus** [comment] 2019-12-11 20:12
What are you sending as a pushRegistrationToken, @AdamBCo ?

**Comment by AdamBCo** [comment] 2019-12-11 20:16
@berkus I am using version 2.2.0 of TwilioChatClient and passing the unmodified deviceToken from the application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) function.

**Comment by berkus** [comment] 2019-12-11 20:47
According to the [changelog](https://www.twilio.com/docs/chat/ios/changelog), you should use 2.6.3 or later, seemingly because of `Fixed handling device token in order to correctly support push notifications on iOS 13.` change.

Could you give 2.6.5 a try and report if that works with pushes better for you?

**Comment by AdamBCo** [comment] 2019-12-11 20:53
@berkus That worked, so thanks for the help. Somewhere in the Twilio documentation it says we should be using version 2.2.0 of the pod file, which will need to be updated. Thanks again.

**Comment by berkus** [comment] 2019-12-11 20:59
If you remember the place - please post the URL here, I'll make sure to go and update that one too.

**Comment by Gray-Wind** [comment] 2019-12-12 08:09
I'm closing this issue, as original problem should be solved. Feel free to left a link in comments here.

**Closed by Gray-Wind** 2019-12-12 08:09 UTC
