### ISSUE TITLE
Carthage support for iOS platform broken

### ISSUE THREAD

**Issue by grioja** [twilio/twilio-chat-ios#1] opened 2018-07-21 16:52 UTC
Have started receiving the following error when doing a Carthage update with `iOS` platform specified:

```
> carthage update --platform ios --cache-builds
*** Skipped building twilio-chat-ios due to the error:
Dependency "twilio-chat-ios" has no shared framework schemes for any of the platforms: iOS
```

Can you add a shared scheme for the `iOS` platform? Otherwise we are forced to use all platforms which greatly slows down Carthage.

**Comment by grioja** [comment] 2018-07-24 15:49
@rbeiter is there anyway we can address this? It was working prior 2.3.x

**Comment by rbeiter** [comment] 2018-07-25 09:14
Hey @grioja – thank you for the @-mention, didn't get pinged on this.  We will investigate and get back to you as soon as possible.

**Comment by rbeiter** [comment] 2018-07-25 09:44
Hi @grioja, I'm having difficulty reproducing this error with the command line above.  As far as I can tell, there will be no shared scheme to add since we distribute the client as a vendored framework with no Xcode project.  The client is distributed as a pre-built binary framework, so I believe the only impact on Carthage should be the size of the binary which is limited when exporting for distribution to just the device architectures using the `remove_archs` script in the build scripts.

Can you provide some information on your Cartfile or the language in use by your project?  Is this preventing the framework from being included or a warning only?

**Comment by grioja** [comment] 2018-07-27 21:50
It's unclear if it's a warning. Swift is our project language.

**Comment by grioja** [comment] 2018-08-04 15:46
Any update here? Can a JSON configuration just be added to this repo to facilitate using the `binary` option?

**Comment by grioja** [comment] 2018-08-08 18:42
@rbeiter can you please setup a hosted json file like other binary-distributed frameworks?

https://building42.github.io/Specs/Carthage/iOS/Fabric.json
https://building42.github.io/Specs/Carthage/iOS/Crashlytics.json

Here is an example for both Fabric and Crashlytics.

Something similar should be setup for `twilio-chat-ios` and `twilio-accessmanager-ios` (and any other binary frameworks)

**Comment by grioja** [comment] 2018-08-08 18:45
Here is an example of what that JSON file might contain:

```
{
    "2.3.3": "https://github.com/twilio/twilio-chat-ios/releases/download/v2.3.3/TwilioChatClient.framework.zip"
}```

**Comment by mromanuk** [comment] 2018-09-06 17:59
Same issue, any update?

**Comment by rbeiter** [comment] 2018-09-06 19:06
Hi @grioja, @mromanuk -

Will the following PR's address this issue for you?  Are you able to test?

AccessManager PR: https://github.com/twilio/twilio-accessmanager-ios/pull/1
Chat PR: https://github.com/twilio/twilio-chat-ios/pull/3
Sync PR: https://github.com/twilio/twilio-sync-ios/pull/1

Using `github` in the Cartfile still works in our testing, as does specifying the new .json file URL's directly, so I want to make sure it solves the issue you both are seeing before merging?

Sample `Cartfile`:

```
binary "https://raw.githubusercontent.com/twilio/twilio-chat-ios/5bdb53148ac308ccaa6515232694d1cbf547d6de/twilio-chat-ios.json"
binary "https://raw.githubusercontent.com/twilio/twilio-accessmanager-ios/315a106d7d5b66ce6cf10d2d8f36abef3096f791/twilio-accessmanager-ios.json"
```

Thank you,
Randy

**Comment by mromanuk** [comment] 2018-09-07 02:17
Hi Randy, I can confirm, that both works!

**Comment by rbeiter** [comment] 2018-09-07 12:48
Thank you, @mromanuk!  One last Q for you before I close this out.  What version of carthage are you on?  I've been testing with `0.30.1`.  Still would like to be able to repro this locally to ensure we don't regress down the road.

**Comment by mromanuk** [comment] 2018-09-07 13:27
@rbeiter I'm using 0.29.0

**Comment by rbeiter** [comment] 2018-09-07 13:35
Thank you again, @mromanuk - the new json manifests are merged in and available.

Thank you @grioja for the help in resolving this.  The json links are:

https://raw.githubusercontent.com/twilio/twilio-chat-ios/master/twilio-chat-ios.json
https://raw.githubusercontent.com/twilio/twilio-accessmanager-ios/master/twilio-accessmanager-ios.json

And for Sync:
https://raw.githubusercontent.com/twilio/twilio-sync-ios/master/twilio-sync-ios.json

**Closed by rbeiter** 2018-09-07 13:35 UTC
