### ISSUE TITLE
Chat client disconnects when app is left idle for long period of time

### ISSUE THREAD

**Issue by uddinr** [twilio/twilio-chat-ios#21] opened 2020-12-02 20:25 UTC
Hi,

We are implementing the Twilio iOS Chat SDK, when the app is sent to the background or left in the foreground idle for a long time, it seems subsequent calls to the sdk seem to timeout.

Is there something we need to do to ensure the client doesnt timeout over long periods of execution? From the twilio documentation here:

https://www.twilio.com/docs/chat/best-practices-sdk-clients

Under sdk lifecycles, do we need to shutdown the client when app goes in background and reinitialise when in the foreground?

**Comment by berkus** [comment] 2020-12-03 10:30
Dupe of https://github.com/twilio/twilio-chat-demo-ios/issues/58

**Closed by berkus** 2020-12-03 10:30 UTC
